import "@/utils/globals.css";

import { Geist, Geist_Mono } from "next/font/google";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import Footer from "@/components/layout/footer";
import type { Metadata } from "next";
import NavBar from "@/components/layout/navbar";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import QueryProvider from "@/components/layout/queryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <NextThemesProvider attribute="class" defaultTheme="light">
            <NavBar />
            <div className="container mx-auto px-4 sm:px-6 md:px-8 lg:px-12 xl:px-16 max-w-7xl">
              {children}
            </div>
          </NextThemesProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
